// ──────────────────────────────────────────────
// Route Registration
// ──────────────────────────────────────────────
import type { FastifyInstance } from "fastify";
import { chatsRoutes } from "./chats.routes.js";
import { chatInsightsRoutes } from "./chat-insights.routes.js";
import { advancedMemoryRoutes } from "./advanced-memory.routes.js";
import { charactersRoutes } from "./characters.routes.js";
import { lorebooksRoutes } from "./lorebooks.routes.js";
import { promptsRoutes } from "./prompts.routes.js";
import { connectionsRoutes } from "./connections.routes.js";
import { agentsRoutes } from "./agents.routes.js";
import { customToolsRoutes } from "./custom-tools.routes.js";
import { generateRoutes } from "./generate.routes.js";
import { utilitySidecarRoutes } from "./utility-sidecar.routes.js";
import { decisionRoutes } from "./decision.routes.js";
import { importRoutes } from "./import.routes.js";
import { backgroundsRoutes } from "./backgrounds.routes.js";
import { avatarsRoutes } from "./avatars.routes.js";
import { spritesRoutes } from "./sprites.routes.js";
import { adminRoutes } from "./admin.routes.js";
import { regexScriptsRoutes } from "./regex-scripts.routes.js";
import { customEmojisRoutes } from "./custom-emojis.routes.js";
import { customStickersRoutes } from "./custom-stickers.routes.js";
import { sceneRoutes } from "./scene.routes.js";
import { fontsRoutes } from "./fonts.routes.js";
import { galleryRoutes } from "./gallery.routes.js";
import { globalGalleryRoutes } from "./global-gallery.routes.js";
import { knowledgeSourcesRoutes } from "./knowledge-sources.routes.js";
import { gifsRoutes } from "./gifs.routes.js";
import { backupRoutes } from "./backup.routes.js";
import { chatFoldersRoutes } from "./chat-folders.routes.js";
import { connectionFoldersRoutes } from "./connection-folders.routes.js";
import { chatPresetsRoutes } from "./chat-presets.routes.js";
import { uiLanguagesRoutes } from "./ui-languages.routes.js";
import { themesRoutes } from "./themes.routes.js";
import { appSettingsRoutes } from "./app-settings.routes.js";
import { achievementsRoutes } from "./achievements.routes.js";
import { gameAssetsRoutes } from "./game-assets.routes.js";
import { sidecarRoutes } from "./sidecar.routes.js";
import { ttsRoutes } from "./tts.routes.js";
import { promptOverridesRoutes } from "./prompt-overrides.routes.js";
import { csrfDiagnosticsRoutes } from "./csrf-diagnostics.routes.js";
import { capabilityPackagesRoutes } from "./capability-packages.routes.js";
import { customAgentRepositoriesRoutes } from "./custom-agent-repositories.routes.js";
import { personalExtensionsRoutes } from "./personal-extensions.routes.js";
import { notificationSoundRoutes } from "./notification-sound.routes.js";
import { libraryFoldersRoutes } from "./library-folders.routes.js";
import { androidLocalAuthRoutes } from "../middleware/android-local-auth.js";

export async function registerRoutes(app: FastifyInstance) {
  // Sibling routes must see the same in-flight generations as the generation plugin.
  if (!app.hasDecorator("activeGenerations")) app.decorate("activeGenerations", new Map());
  await app.register(androidLocalAuthRoutes, { prefix: "/api/android-auth" });
  await app.register(chatsRoutes, { prefix: "/api/chats" });
  await app.register(advancedMemoryRoutes, { prefix: "/api/chats" });
  await app.register(chatInsightsRoutes, { prefix: "/api/chat-insights" });
  await app.register(chatFoldersRoutes, { prefix: "/api/chat-folders" });
  await app.register(chatPresetsRoutes, { prefix: "/api/chat-presets" });
  await app.register(charactersRoutes, { prefix: "/api/characters" });
  await app.register(lorebooksRoutes, { prefix: "/api/lorebooks" });
  await app.register(promptsRoutes, { prefix: "/api/prompts" });
  await app.register(connectionsRoutes, { prefix: "/api/connections" });
  await app.register(decisionRoutes, { prefix: "/api/decision" });
  await app.register(connectionFoldersRoutes, { prefix: "/api/connection-folders" });
  await app.register(libraryFoldersRoutes, { prefix: "/api/library-folders" });
  await app.register(agentsRoutes, { prefix: "/api/agents" });
  await app.register(utilitySidecarRoutes, { prefix: "/api/utility-sidecar" });
  await app.register(customToolsRoutes, { prefix: "/api/custom-tools" });
  await app.register(generateRoutes, { prefix: "/api/generate" });
  await app.register(importRoutes, { prefix: "/api/import" });
  await app.register(backgroundsRoutes, { prefix: "/api/backgrounds" });
  await app.register(avatarsRoutes, { prefix: "/api/avatars" });
  await app.register(spritesRoutes, { prefix: "/api/sprites" });
  await app.register(adminRoutes, { prefix: "/api/admin" });
  await app.register(regexScriptsRoutes, { prefix: "/api/regex-scripts" });
  await app.register(customEmojisRoutes, { prefix: "/api/custom-emojis" });
  await app.register(customStickersRoutes, { prefix: "/api/custom-stickers" });
  await app.register(sceneRoutes, { prefix: "/api/scene" });
  await app.register(fontsRoutes, { prefix: "/api/fonts" });
  await app.register(galleryRoutes, { prefix: "/api/gallery" });
  await app.register(globalGalleryRoutes, { prefix: "/api/global-gallery" });
  await app.register(knowledgeSourcesRoutes, { prefix: "/api/knowledge-sources" });
  await app.register(gifsRoutes, { prefix: "/api/gifs" });
  await app.register(backupRoutes, { prefix: "/api/backup" });
  await app.register(uiLanguagesRoutes, { prefix: "/api/ui-languages" });
  await app.register(themesRoutes, { prefix: "/api/themes" });
  await app.register(appSettingsRoutes, { prefix: "/api/app-settings" });
  await app.register(achievementsRoutes, { prefix: "/api/achievements" });
  await app.register(gameAssetsRoutes, { prefix: "/api/game-assets" });
  await app.register(ttsRoutes, { prefix: "/api/tts" });
  await app.register(promptOverridesRoutes, { prefix: "/api/prompt-overrides" });
  await app.register(csrfDiagnosticsRoutes, { prefix: "/api/csrf" });
  await app.register(capabilityPackagesRoutes, { prefix: "/api/capability-packages" });
  await app.register(customAgentRepositoriesRoutes, { prefix: "/api/custom-agent-repositories" });
  await app.register(personalExtensionsRoutes, { prefix: "/api/personal-extensions" });
  await app.register(notificationSoundRoutes, { prefix: "/api/notification-sound" });
  if (process.env.MARINARA_LITE !== "true" && process.env.MARINARA_LITE !== "1") {
    await app.register(sidecarRoutes, { prefix: "/api/sidecar" });
  }
}
